In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random

In [2]:
df = pd.read_csv("C:/Users/Tim/OneDrive/Desktop/Uber_data.csv")

In [3]:
df.columns

Index(['hvfhs_license_num', 'dispatching_base_num', 'originating_base_num',
       'request_datetime', 'on_scene_datetime', 'pickup_datetime',
       'dropoff_datetime', 'PULocationID', 'DOLocationID', 'trip_miles',
       'trip_time', 'base_passenger_fare', 'tolls', 'bcf', 'sales_tax',
       'congestion_surcharge', 'airport_fee', 'tips', 'driver_pay',
       'shared_request_flag', 'shared_match_flag', 'access_a_ride_flag',
       'wav_request_flag', 'wav_match_flag', 'day_of_week', 'hour_of_day',
       'time_of_day', 'week_period', 'Borough', 'Zone', 'service_zone'],
      dtype='object')

In [4]:
df.shape

(13998413, 31)

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,day_of_week,hour_of_day,time_of_day,week_period,Borough,Zone,service_zone
0,HV0003,B03404,B03404,2023-03-31 20:01:28,2023-03-31 20:02:41,2023-03-31 20:03:03,2023-03-31 20:15:42,174,126,5.10,759,20.52,0.0,0.62,1.82,0.00,0.0,0.00,13.83,N,N,,N,N,Friday,20,other,weekday evening,Bronx,Norwood,Boro Zone
1,HV0003,B03404,B03404,2023-03-31 20:39:40,2023-03-31 20:41:20,2023-03-31 20:43:42,2023-03-31 21:01:08,211,163,3.11,1046,40.12,0.0,1.20,3.56,2.75,0.0,9.52,24.84,N,N,,N,N,Friday,20,other,weekday evening,Manhattan,SoHo,Yellow Zone
2,HV0003,B03404,B03404,2023-03-31 19:56:31,2023-03-31 20:00:20,2023-03-31 20:01:01,2023-03-31 20:09:48,222,76,2.40,527,12.16,0.0,0.36,1.08,0.00,0.0,0.00,8.10,Y,N,,N,N,Friday,19,other,weekday evening,Brooklyn,Starrett City,Boro Zone
3,HV0003,B03404,B03404,2023-03-31 20:12:35,2023-03-31 20:16:04,2023-03-31 20:17:17,2023-03-31 20:19:12,76,124,0.43,115,7.86,0.0,0.24,0.70,0.00,0.0,0.00,5.40,N,N,,N,N,Friday,20,other,weekday evening,Brooklyn,East New York,Boro Zone
4,HV0003,B03404,B03404,2023-03-31 20:46:23,2023-03-31 20:47:30,2023-03-31 20:47:49,2023-03-31 21:05:23,263,247,4.18,1054,16.73,0.0,0.50,1.48,2.75,0.0,0.00,15.65,N,N,,N,N,Friday,20,other,weekday evening,Manhattan,Yorkville West,Yellow Zone

In [6]:
columns_to_convert = ['shared_request_flag', 'shared_match_flag']

df[columns_to_convert] = df[columns_to_convert].apply(lambda x: x.map({'Y': 1, 'N': 0}))

In [7]:
columns_to_drop = ['access_a_ride_flag', 'wav_request_flag', 'wav_match_flag']

# Use the drop method to remove the specified columns
df = df.drop(columns=columns_to_drop)

In [8]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,day_of_week,hour_of_day,time_of_day,week_period,Borough,Zone,service_zone
0,HV0003,B03404,B03404,2023-03-31 20:01:28,2023-03-31 20:02:41,2023-03-31 20:03:03,2023-03-31 20:15:42,174,126,5.10,759,20.52,0.0,0.62,1.82,0.00,0.0,0.00,13.83,0,0,Friday,20,other,weekday evening,Bronx,Norwood,Boro Zone
1,HV0003,B03404,B03404,2023-03-31 20:39:40,2023-03-31 20:41:20,2023-03-31 20:43:42,2023-03-31 21:01:08,211,163,3.11,1046,40.12,0.0,1.20,3.56,2.75,0.0,9.52,24.84,0,0,Friday,20,other,weekday evening,Manhattan,SoHo,Yellow Zone
2,HV0003,B03404,B03404,2023-03-31 19:56:31,2023-03-31 20:00:20,2023-03-31 20:01:01,2023-03-31 20:09:48,222,76,2.40,527,12.16,0.0,0.36,1.08,0.00,0.0,0.00,8.10,1,0,Friday,19,other,weekday evening,Brooklyn,Starrett City,Boro Zone
3,HV0003,B03404,B03404,2023-03-31 20:12:35,2023-03-31 20:16:04,2023-03-31 20:17:17,2023-03-31 20:19:12,76,124,0.43,115,7.86,0.0,0.24,0.70,0.00,0.0,0.00,5.40,0,0,Friday,20,other,weekday evening,Brooklyn,East New York,Boro Zone
4,HV0003,B03404,B03404,2023-03-31 20:46:23,2023-03-31 20:47:30,2023-03-31 20:47:49,2023-03-31 21:05:23,263,247,4.18,1054,16.73,0.0,0.50,1.48,2.75,0.0,0.00,15.65,0,0,Friday,20,other,weekday evening,Manhattan,Yorkville West,Yellow Zone

In [9]:
df['tolls'] = df['tolls'].apply(lambda x: 1 if x > 0 else 0)

df['congestion_surcharge'] = df['congestion_surcharge'].apply(lambda x: 1 if x > 0 else 0)

In [10]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,day_of_week,hour_of_day,time_of_day,week_period,Borough,Zone,service_zone
0,HV0003,B03404,B03404,2023-03-31 20:01:28,2023-03-31 20:02:41,2023-03-31 20:03:03,2023-03-31 20:15:42,174,126,5.10,759,20.52,0,0.62,1.82,0,0.0,0.00,13.83,0,0,Friday,20,other,weekday evening,Bronx,Norwood,Boro Zone
1,HV0003,B03404,B03404,2023-03-31 20:39:40,2023-03-31 20:41:20,2023-03-31 20:43:42,2023-03-31 21:01:08,211,163,3.11,1046,40.12,0,1.20,3.56,1,0.0,9.52,24.84,0,0,Friday,20,other,weekday evening,Manhattan,SoHo,Yellow Zone
2,HV0003,B03404,B03404,2023-03-31 19:56:31,2023-03-31 20:00:20,2023-03-31 20:01:01,2023-03-31 20:09:48,222,76,2.40,527,12.16,0,0.36,1.08,0,0.0,0.00,8.10,1,0,Friday,19,other,weekday evening,Brooklyn,Starrett City,Boro Zone
3,HV0003,B03404,B03404,2023-03-31 20:12:35,2023-03-31 20:16:04,2023-03-31 20:17:17,2023-03-31 20:19:12,76,124,0.43,115,7.86,0,0.24,0.70,0,0.0,0.00,5.40,0,0,Friday,20,other,weekday evening,Brooklyn,East New York,Boro Zone
4,HV0003,B03404,B03404,2023-03-31 20:46:23,2023-03-31 20:47:30,2023-03-31 20:47:49,2023-03-31 21:05:23,263,247,4.18,1054,16.73,0,0.50,1.48,1,0.0,0.00,15.65,0,0,Friday,20,other,weekday evening,Manhattan,Yorkville West,Yellow Zone

In [11]:
tolls_count = (df['tolls'] == 1).sum()
tolls_count

1561871

In [12]:
cc = (df['congestion_surcharge'] == 1).sum()
cc

6033836

In [13]:
srf_count = (df['shared_request_flag'] == 1).sum()
srf_count

328486

In [21]:
df.to_csv('uber_585', index=False)

In [15]:
tolls_present = df['tolls'] > 0
percentage_with_tolls = (tolls_present.sum() / len(df)) * 100

print(f"Percentage of samples containing tolls: {percentage_with_tolls:.2f}%")

# Check for congestion surcharge
congestion_surcharge_present = df['congestion_surcharge'] > 0
percentage_with_congestion_surcharge = (congestion_surcharge_present.sum() / len(df)) * 100

print(f"Percentage of samples containing congestion surcharge: {percentage_with_congestion_surcharge:.2f}%")


srf_present = df['shared_request_flag'] > 0
percentage_with_srf = (srf_present.sum() / len(df)) * 100

print(f"Percentage of samples containing srf: {percentage_with_srf:.2f}%")

Percentage of samples containing tolls: 11.16%
Percentage of samples containing congestion surcharge: 43.10%
Percentage of samples containing srf: 2.35%

In [17]:
import numpy as np
# Set the seed for reproducibility
seed_value = 42
np.random.seed(seed_value)

# Sample size
total_samples = 50000

# Number of samples for each condition
samples_with_shared_request_flag = int(0.0235 * total_samples)
samples_with_tolls = int(0.1116 * total_samples)
samples_with_congestion_surcharge = int(0.431 * total_samples)

# Randomly sample rows with shared request flag
df_shared_request_flag = df[df['shared_request_flag'] > 0].sample(n=samples_with_shared_request_flag, random_state=seed_value)

# Randomly sample rows with tolls
df_tolls = df[df['tolls'] > 0].sample(n=samples_with_tolls, random_state=seed_value)

# Randomly sample rows with congestion surcharge
df_congestion_surcharge = df[df['congestion_surcharge'] > 0].sample(n=samples_with_congestion_surcharge, random_state=seed_value)

# Concatenate the DataFrames
df_final = pd.concat([df_shared_request_flag, df_tolls, df_congestion_surcharge], ignore_index=True)

# If the total number of samples is less than 50,000, fill the remaining with random samples
if len(df_final) < total_samples:
    remaining_samples = total_samples - len(df_final)
    df_remaining = df.sample(n=remaining_samples, random_state=seed_value)
    df_final = pd.concat([df_final, df_remaining], ignore_index=True)

# Shuffle the final DataFrame
df_final = df_final.sample(frac=1, random_state=seed_value).reset_index(drop=True)

In [18]:
df_final.shape

(50000, 28)

In [20]:
df_final.to_csv('uber_df_final', index=False)

In [19]:
tolls_present_final = df_final['tolls'] > 0
percentage_with_tolls_final = (tolls_present_final.sum() / len(df_final)) * 100

print(f"Percentage of samples containing tolls in df_final: {percentage_with_tolls_final:.2f}%")

# Check for congestion surcharge
congestion_surcharge_present_final = df_final['congestion_surcharge'] > 0
percentage_with_congestion_surcharge_final = (congestion_surcharge_present_final.sum() / len(df_final)) * 100

print(f"Percentage of samples containing congestion surcharge in df_final: {percentage_with_congestion_surcharge_final:.2f}%")

# Check for shared request flag
srf_present_final = df_final['shared_request_flag'] > 0
percentage_with_srf_final = (srf_present_final.sum() / len(df_final)) * 100

print(f"Percentage of samples containing shared request flag in df_final: {percentage_with_srf_final:.2f}%")

Percentage of samples containing tolls in df_final: 21.82%
Percentage of samples containing congestion surcharge in df_final: 68.21%
Percentage of samples containing shared request flag in df_final: 4.43%

In [ ]:
# Sample size
total_samples = 50000

# Number of samples for each condition
samples_with_tolls = int(0.1116 * total_samples)
samples_with_congestion_surcharge = int(0.431 * total_samples)
samples_with_shared_request_flag = int(0.0235 * total_samples)

# Randomly sample rows with tolls
df_tolls = df[df['tolls'] > 0].sample(n=samples_with_tolls, random_state=seed_value)

# Randomly sample rows with congestion surcharge
df_congestion_surcharge = df[df['congestion_surcharge'] > 0].sample(n=samples_with_congestion_surcharge, random_state=seed_value)

# Randomly sample rows with shared request flag
df_shared_request_flag = df[df['shared_request_flag'] > 0].sample(n=samples_with_shared_request_flag, random_state=seed_value)

In [31]:
df.shape

(13998413, 28)

In [61]:

desired_sample_size = 50000
desired_srf_percentage = 65 

# figure out the number of rows needed for each category
num_srf = int(desired_sample_size * (desired_srf_percentage / 100))
num_others = desired_sample_size - num_srf

# sample rows where shared_request_flag is 1
df_srf = df[df['shared_request_flag'] == 1].sample(n=num_srf, replace=True)

# sample remaining rows where shared_request_flag is not 1
df_others = df[df['shared_request_flag'] != 1].sample(n=num_others, replace=True)


df_sample = pd.concat([df_flag_1, df_others]).sample(frac=1)

In [62]:
srf = (df_sample['shared_request_flag'] == 1).sum()
srf
cc = (df_sample['congestion_surcharge'] == 1).sum()
cc
t = (df_sample['congestion_surcharge'] == 1).sum()
t
print(t)
print(srf)
print(cc)

19655
32500
19655

In [63]:
df_sample.shape

(50000, 28)

In [ ]:
import random
percent_of_non_zeros = 65
df_non_zeros = df[(df['shared_request_flag'] == 'Y') | (df['tolls'] != 0) | (df['congestion_surcharge'] != 0)].sample(percent_of_non_zeros*len(df))
percent_of_zeros = 1 - percent_of_non_zeros
df_others = df[~df.index.isin(df_non_zeros.index)]
df_others = df_others.sample(percent_of_zeros*len(df))

In [15]:
sample_size = 50000
percent_of_non_zeros = 65

# identify rows satisfying at least one condition
condition_mask = (df['shared_request_flag'] == 1) | (df['tolls'] != 0) | (df['congestion_surcharge'] != 0)
df_satisfying_conditions = df[condition_mask]

# figure out the number of rows needed for each category
num_non_zeros = int(sample_size * (percent_of_non_zeros / 100))
num_others = sample_size - num_non_zeros

# sample rows satisfying at least one condition
df_non_zeros = df_satisfying_conditions.sample(n=num_non_zeros, replace=False)

# sample remaining rows
df_others = df_satisfying_conditions[~df_satisfying_conditions.index.isin(df_non_zeros.index)].sample(n=num_others, replace=False)


df_sample = pd.concat([df_non_zeros, df_others]).sample(frac=1)

In [16]:
srf = (df_sample['shared_request_flag'] == 1).sum()
srf
cc = (df_sample['congestion_surcharge'] == 1).sum()
cc
t = (df_sample['congestion_surcharge'] == 1).sum()
t
print(t)
print(srf)
print(cc)

43102
2384
43102

In [70]:
df_sample.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,day_of_week,hour_of_day,time_of_day,week_period,Borough,Zone,service_zone
7061999,HV0003,B03404,B03404,2023-04-16 08:19:23,2023-04-16 08:20:44,2023-04-16 08:21:14,2023-04-16 08:37:08,231,246,2.55,954,25.73,0,0.77,2.28,1,0.0,0.0,14.54,0,0,Sunday,8,other,weekend day,Manhattan,TriBeCa/Civic Center,Yellow Zone
4273054,HV0003,B03404,B03404,2023-04-10 07:44:08,2023-04-10 07:46:41,2023-04-10 07:47:29,2023-04-10 08:03:46,262,88,7.72,977,19.90,0,0.60,1.77,1,0.0,2.5,19.37,0,0,Monday,7,Morning rush,weekday day,Manhattan,Yorkville East,Yellow Zone
5839174,HV0003,B03404,B03404,2023-04-14 03:45:34,2023-04-14 03:49:13,2023-04-14 03:49:17,2023-04-14 03:58:19,239,50,1.45,542,9.98,0,0.30,0.89,1,0.0,3.0,7.00,0,0,Friday,3,Slow morning,other,Manhattan,Upper West Side South,Yellow Zone
2824378,HV0003,B03404,B03404,2023-04-07 05:12:02,2023-04-07 05:12:30,2023-04-07 05:13:24,2023-04-07 05:33:17,148,181,4.11,1193,18.60,0,0.56,1.65,1,0.0,0.0,16.89,0,0,Friday,5,Morning rush,weekday day,Manhattan,Lower East Side,Yellow Zone
3555251,HV0003,B03404,B03404,2023-04-08 15:41:33,2023-04-08 15:47:44,2023-04-08 15:48:27,2023-04-08 16:08:27,244,230,8.05,1200,36.34,0,1.09,3.23,1,0.0,0.0,26.66,0,0,Saturday,15,other,weekend day,Manhattan,Washington Heights South,Boro Zone

how to do now do a logistic regression where.       shared_request_flag is dep. variable, and indipendnat vairbalesa are, b0 + b1(total_fee)(interacitve term, base_passenger_fee+sales_tax)

In [67]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [71]:
# Create the interaction term
df_sample['total_fee_interaction'] = df_sample['base_passenger_fare'] * df_sample['sales_tax']

# Define independent variables
independent_vars = ['trip_miles', 'trip_time', 'total_fee_interaction', 'tolls', 'congestion_surcharge', 'time_of_day', 'Borough', 'airport_fee']

# Create design matrix (X) and target variable (y)
X = df_sample[independent_vars]
y = df_sample['shared_request_flag']

# Convert categorical variables to dummy variables
X = pd.get_dummies(X, columns=['time_of_day', 'Borough', 'airport_fee'], drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Fit logistic regression model
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

# Predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Get coefficients and intercept
coefficients = log_reg.coef_
intercept = log_reg.intercept_

print("Coefficients:", coefficients)
print("Intercept:", intercept)

[[9527    2]
 [ 192  279]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      9529
           1       0.99      0.59      0.74       471

    accuracy                           0.98     10000
   macro avg       0.99      0.80      0.87     10000
weighted avg       0.98      0.98      0.98     10000

Coefficients: [[-0.73589714  0.81119775 -1.78356156 -1.91868584 -1.71082855 -0.0701486
   0.1766822  -0.16625891 -0.08121283 -0.55745853 -0.02595283  0.03649417
   0.          0.68301978 -0.80342958 -0.12373859]]
Intercept: [-4.60565876]

In [72]:
df_sample['total_base'] = df_sample['base_passenger_fare'] + df_sample['sales_tax']

In [74]:
df_sample.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,day_of_week,hour_of_day,time_of_day,week_period,Borough,Zone,service_zone,total_fee_interaction,total_base
7061999,HV0003,B03404,B03404,2023-04-16 08:19:23,2023-04-16 08:20:44,2023-04-16 08:21:14,2023-04-16 08:37:08,231,246,2.55,954,25.73,0,0.77,2.28,1,0.0,0.0,14.54,0,0,Sunday,8,other,weekend day,Manhattan,TriBeCa/Civic Center,Yellow Zone,58.6644,28.01
4273054,HV0003,B03404,B03404,2023-04-10 07:44:08,2023-04-10 07:46:41,2023-04-10 07:47:29,2023-04-10 08:03:46,262,88,7.72,977,19.90,0,0.60,1.77,1,0.0,2.5,19.37,0,0,Monday,7,Morning rush,weekday day,Manhattan,Yorkville East,Yellow Zone,35.2230,21.67
5839174,HV0003,B03404,B03404,2023-04-14 03:45:34,2023-04-14 03:49:13,2023-04-14 03:49:17,2023-04-14 03:58:19,239,50,1.45,542,9.98,0,0.30,0.89,1,0.0,3.0,7.00,0,0,Friday,3,Slow morning,other,Manhattan,Upper West Side South,Yellow Zone,8.8822,10.87
2824378,HV0003,B03404,B03404,2023-04-07 05:12:02,2023-04-07 05:12:30,2023-04-07 05:13:24,2023-04-07 05:33:17,148,181,4.11,1193,18.60,0,0.56,1.65,1,0.0,0.0,16.89,0,0,Friday,5,Morning rush,weekday day,Manhattan,Lower East Side,Yellow Zone,30.6900,20.25
3555251,HV0003,B03404,B03404,2023-04-08 15:41:33,2023-04-08 15:47:44,2023-04-08 15:48:27,2023-04-08 16:08:27,244,230,8.05,1200,36.34,0,1.09,3.23,1,0.0,0.0,26.66,0,0,Saturday,15,other,weekend day,Manhattan,Washington Heights South,Boro Zone,117.3782,39.57

In [76]:
df_sample.to_csv('uber_random_sample.csv', index=False)

In [ ]:
df_sample.to_csv('df_sample.csv', index=False)